export enum IconType {
  LOADING = 'loading',
  SEARCH = 'search',
  CLOSE = 'close',
  DELETE = 'delete',
  ARROW = 'arrow',
  ARROW_2 = 'arrow-2',
  DATE_PICKER = 'datepicker',
  LIGHT_OR_DARK = 'lightOrDark',
  VOICE = 'voice',
  USER = 'user',
  PHOTO = 'photo',
  GITHUB = 'github',
  JUEJIN = 'juejin',
}
